version: "3.1"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # expose:
    #   - "3000"
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"